blank_issues_enabled: false
contact_links:
  - name: LinkedIn
    url: https://www.linkedin.com/in/dario-varriale/
    about: Please send me a message on LinkedIn!
  - name: Email
    url: mailto:dariovarrialeapps@gmail.com
    about: You can send me an email here!
