import 'package:flutter/material.dart';

import '../../password_strength_checker.dart';

/// Extension on [TextFormField] to create a [TextFormField] based on the
/// [TextFormFieldConfiguration].
extension FromConfig on TextFormField {
  /// Crea un [TextFormField] basato su [TextFormFieldConfiguration].
  TextFormField fromConfig(
      {required TextFormFieldConfiguration configuration}) {
    return TextFormField(
      key: configuration.key,
      groupId: configuration.groupId,
      controller: configuration.controller,
      initialValue: configuration.initialValue,
      focusNode: configuration.focusNode,
      forceErrorText: configuration.forceErrorText,
      decoration: configuration.decoration,
      keyboardType: configuration.keyboardType,
      textCapitalization: configuration.textCapitalization,
      textInputAction: configuration.textInputAction,
      style: configuration.style,
      strutStyle: configuration.strutStyle,
      textDirection: configuration.textDirection,
      textAlign: configuration.textAlign,
      textAlignVertical: configuration.textAlignVertical,
      autofocus: configuration.autofocus,
      readOnly: configuration.readOnly,
      toolbarOptions: configuration.toolbarOptions,
      showCursor: configuration.showCursor,
      obscuringCharacter: configuration.obscuringCharacter,
      obscureText: configuration.obscureText,
      autocorrect: configuration.autocorrect,
      smartDashesType: configuration.smartDashesType,
      smartQuotesType: configuration.smartQuotesType,
      enableSuggestions: configuration.enableSuggestions,
      maxLengthEnforcement: configuration.maxLengthEnforcement,
      maxLines: configuration.maxLines,
      minLines: configuration.minLines,
      expands: configuration.expands,
      maxLength: configuration.maxLength,
      onChanged: configuration.onChanged,
      onTap: configuration.onTap,
      onTapAlwaysCalled: configuration.onTapAlwaysCalled,
      onTapOutside: configuration.onTapOutside,
      onTapUpOutside: configuration.onTapUpOutside,
      onEditingComplete: configuration.onEditingComplete,
      onFieldSubmitted: configuration.onFieldSubmitted,
      onSaved: configuration.onSaved,
      validator: configuration.validator,
      errorBuilder: configuration.errorBuilder,
      inputFormatters: configuration.inputFormatters,
      enabled: configuration.enabled,
      ignorePointers: configuration.ignorePointers,
      cursorWidth: configuration.cursorWidth,
      cursorHeight: configuration.cursorHeight,
      cursorRadius: configuration.cursorRadius,
      cursorColor: configuration.cursorColor,
      cursorErrorColor: configuration.cursorErrorColor,
      keyboardAppearance: configuration.keyboardAppearance,
      scrollPadding: configuration.scrollPadding,
      enableInteractiveSelection: configuration.enableInteractiveSelection,
      selectAllOnFocus: configuration.selectAllOnFocus,
      selectionControls: configuration.selectionControls,
      buildCounter: configuration.buildCounter,
      scrollPhysics: configuration.scrollPhysics,
      autofillHints: configuration.autofillHints,
      autovalidateMode: configuration.autovalidateMode,
      scrollController: configuration.scrollController,
      restorationId: configuration.restorationId,
      enableIMEPersonalizedLearning:
          configuration.enableIMEPersonalizedLearning,
      mouseCursor: configuration.mouseCursor,
      contextMenuBuilder: configuration.contextMenuBuilder,
      spellCheckConfiguration: configuration.spellCheckConfiguration,
      magnifierConfiguration: configuration.magnifierConfiguration,
      undoController: configuration.undoController,
      onAppPrivateCommand: configuration.onAppPrivateCommand,
      cursorOpacityAnimates: configuration.cursorOpacityAnimates,
      selectionHeightStyle: configuration.selectionHeightStyle,
      selectionWidthStyle: configuration.selectionWidthStyle,
      dragStartBehavior: configuration.dragStartBehavior,
      contentInsertionConfiguration:
          configuration.contentInsertionConfiguration,
      statesController: configuration.statesController,
      clipBehavior: configuration.clipBehavior,
      scribbleEnabled: configuration.scribbleEnabled,
      stylusHandwritingEnabled: configuration.stylusHandwritingEnabled,
      canRequestFocus: configuration.canRequestFocus,
      hintLocales: configuration.hintLocales,
    );
  }
}
